---
AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Create one or more EFS filesystems (aws-cfn-gen version: {{ gittag | default('na') }})


Resources:
{% for filesystem in efs %}
  {{ filesystem.cfn_name }}:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true
      FileSystemTags:
        - Key: Application
          Value: "{{ application }}"
        - Key: Environment
          Value: "{{ env }}"
        - Key: Customer
          Value: "{{ customer | default('NA') }}"

  {{ filesystem.cfn_name }}MountTargetPrivateSubnetAZ1:
    Type: AWS::EFS::MountTarget
    Properties:
      FilesystemId: !Ref {{ filesystem.cfn_name }}
      SecurityGroups:
        - "{{ vpc_sg_app }}"
      SubnetId: "{{ vpc_privatesubnet_az1 }}"

  {{ filesystem.cfn_name }}MountTargetPrivateSubnetAZ2:
    Type: AWS::EFS::MountTarget
    Properties:
      FilesystemId: !Ref {{ filesystem.cfn_name }}
      SecurityGroups:
        - "{{ vpc_sg_app }}"
      SubnetId: "{{ vpc_privatesubnet_az2 }}"

{%   if vpc_nr_of_azs == "3" %}
  {{ filesystem.cfn_name }}MountTargetPrivateSubnetAZ3:
    Type: AWS::EFS::MountTarget
    Properties:
      FilesystemId: !Ref {{ filesystem.cfn_name }}
      SecurityGroups:
        - "{{ vpc_sg_app }}"
      SubnetId: "{{ vpc_privatesubnet_az3 }}"
{%   endif %}

{% endfor %}

Outputs:
{% for filesystem in efs %}
  {{ filesystem.cfn_name }}Output:
    Value: !Ref {{ filesystem.cfn_name }}
    Description: "EFS File System ID"
    Export:
      Name: !Sub "${AWS::StackName}{{ filesystem.cfn_name }}"

{% endfor %}