AWSTemplateFormatVersion: '2010-09-09'

Description: |
  Create one or more EFS filesystems (aws-cfn-gen version: {{ gittag | default('na') }})

Resources:
{% for filesystem in efs %}
  {{ filesystem.cfn_name }}:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true
      FileSystemTags:
        - Key: Application
          Value: "{{ application }}"
        - Key: Environment
          Value: "{{ env }}"
        - Key: Customer
          Value: "{{ customer | default('NA') }}"

  {{ filesystem.cfn_name }}MountTargetPrivateSubnetAZ1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref {{ filesystem.cfn_name }}
      SecurityGroups:
        - "{{ vpc_sg_app }}"
      SubnetId: "{{ vpc_privatesubnet_az1 }}"

  {{ filesystem.cfn_name }}MountTargetPrivateSubnetAZ2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref {{ filesystem.cfn_name }}
      SecurityGroups:
        - "{{ vpc_sg_app }}"
      SubnetId: "{{ vpc_privatesubnet_az2 }}"

{%   if vpc_nr_of_azs == "3" %}
  {{ filesystem.cfn_name }}MountTargetPrivateSubnetAZ3:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref {{ filesystem.cfn_name }}
      SecurityGroups:
        - "{{ vpc_sg_app }}"
      SubnetId: "{{ vpc_privatesubnet_az3 }}"
{%   endif %}
{%   for accesspoint in filesystem.accesspoints | default([]) %}

  {{ accesspoint.cfn_name }}:
    Type: AWS::EFS::AccessPoint
    Properties:
      FileSystemId: !Ref {{ filesystem.cfn_name }}
{%     if accesspoint.posix_user is defined %}
      PosixUser:
        Uid: "{{ accesspoint.posix_user.uid | default('0') }}"
        Gid: "{{ accesspoint.posix_user.gid | default('0') }}"
{%       if accesspoint.posix_user.secondary_gids is defined %}
        SecondaryGids:
{%         for gid in accesspoint.posix_user.secondary_gids %}
          - "{{ gid }}"
{%         endfor %}
{%       endif %}
{%     endif %}
      RootDirectory:
        Path: {{ accesspoint.path | default('/') }}
{%     if accesspoint.creation_info is defined %}
        CreationInfo:
          OwnerGid: "{{ accesspoint.creation_info.owner_gid | default('0') }}"
          OwnerUid: "{{ accesspoint.creation_info.owner_uid | default('0') }}"
          Permissions: "{{ accesspoint.creation_info.permissions | default('0755') }}"
{%     endif %}

{%   endfor %}

{% endfor %}

Outputs:
{% for filesystem in efs %}
  {{ filesystem.cfn_name }}Output:
    Value: !Ref {{ filesystem.cfn_name }}
    Description: "EFS File System ID"
    Export:
      Name: !Sub "${AWS::StackName}{{ filesystem.cfn_name }}"

{% endfor %}